name: Daily Bitcoin News

on:
  schedule:
    - cron: '0 11 * * *' # 한국 시간 저녁 8시 (UTC 11:00)
  workflow_dispatch: # 수동 실행 버튼

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 lxml

      - name: Run script
        run: python news.py
